site_name: Taxonomy Development Tools (TDT)
theme: readthedocs
#markdown_extensions:
#  - toc:
#      permalink: true
nav:
  - Getting started: index.md
  - Create a New Repo: NewRepo.md
  - Get TDT Docker Image: Build.md
  - Start Curating Taxonomies: Curation.md
repo_url: https://github.com/brain-bican/taxonomy-development-tools
