site_name: Taxonomy Development Tools (TDT)
theme: readthedocs
#markdown_extensions:
#  - toc:
#      permalink: true
nav:
  - Getting started: index.md
  - Quick Start Guide: QuickStart.md
  - Introduction to TDT: Intro_to_TDT.md
  - Install Requirements: Build.md
  - Create a New Repo: NewRepo.md
  - Start Curating Taxonomies: Curation.md
  - User Interface: UserInterface.md
  - How-to guides:
    -  Update to a newer TDT version: Update.md
repo_url: https://github.com/brain-bican/taxonomy-development-tools/tree/main/docs
