site_name: Taxonomy Development Tools (TDT)
theme: readthedocs
#markdown_extensions:
#  - toc:
#      permalink: true
nav:
  - Getting started: index.md
repo_url: https://github.com/hkir-dev/taxonomy-development-tools
